<body>
    <table>
        <thead>
        <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Rôle</th>
            <th>Actif</th>
        </thead>
        <tbody>
        <?php foreach($users as $user):?>
                <tr>
                    <td><?=$user['u_firstname']?></td>
                    <td><?=$user['u_lastname']?></td>
                    <td><?=$user['u_email']?></td>
                    <td><?=ROLES[$user['u_role']]?></td>
                    <td><?=$user['u_valide']?><</td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>

</body>